using Procraft.Application.Common.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Procraft.Infrastructure.Pdf;

public sealed class QuestPdfService : IPdfService
{
    private const string UploadsPublicOrigin = "https://api.procraft.uz";

    private static readonly string HeadingColor = Colors.BlueGrey.Darken4;
    private static readonly string MutedColor = Colors.Grey.Darken2;
    private static readonly string RuleColor = Colors.Grey.Lighten2;
    private static readonly string LinkColor = Colors.Blue.Darken2;

    public Task<byte[]> GenerateResumeAsync(PdfResumeModel resume, CancellationToken cancellationToken = default)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var bytes = Document.Create(document =>
        {
            document.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(34);
                page.DefaultTextStyle(text => text.FontFamily("Arial").FontSize(9.5f).LineHeight(1.28f));

                page.Content().Column(column =>
                {
                    column.Spacing(11);
                    ComposeHeader(column, resume);
                    ComposeSummary(column, resume);
                    ComposeExperiences(column, resume.Experiences);
                    ComposeEducations(column, resume.Educations);
                    ComposeSkills(column, resume.Skills);
                    ComposeProjects(column, resume.Projects);
                    ComposeCertificates(column, resume.Certificates);
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Procraft").FontSize(8).FontColor(Colors.Grey.Darken1);
                });
            });
        }).GeneratePdf();

        return Task.FromResult(bytes);
    }

    private static void ComposeHeader(ColumnDescriptor column, PdfResumeModel resume)
    {
        column.Item().Row(row =>
        {
            row.RelativeItem().Column(left =>
            {
                left.Spacing(4);
                left.Item().Text(resume.FullName).FontSize(24).Bold().FontColor(HeadingColor);

                if (!string.IsNullOrWhiteSpace(resume.Title))
                {
                    left.Item().Text(resume.Title).FontSize(12).SemiBold().FontColor(Colors.BlueGrey.Darken2);
                }

                if (!string.IsNullOrWhiteSpace(resume.Location))
                {
                    left.Item().Text(text =>
                    {
                        text.Span("Joylashuv: ").SemiBold().FontColor(MutedColor);
                        text.Span(resume.Location).FontColor(MutedColor);
                    });
                }
            });

            if (resume.SocialLinks.Count > 0)
            {
                row.ConstantItem(190).Column(right =>
                {
                    right.Spacing(3);
                    right.Item().Text("Ijtimoiy havolalar").FontSize(8).Bold().FontColor(HeadingColor);

                    foreach (var link in resume.SocialLinks)
                    {
                        AddLinkLine(right, link.Platform, link.Url, 8);
                    }
                });
            }
        });

        column.Item().BorderBottom(1).BorderColor(RuleColor).PaddingTop(2);
    }

    private static void ComposeSummary(ColumnDescriptor column, PdfResumeModel resume)
    {
        if (string.IsNullOrWhiteSpace(resume.Summary))
        {
            return;
        }

        ComposeSection(column, "Qisqa ma'lumot", section =>
        {
            section.Item().Text(resume.Summary).FontSize(9.5f).FontColor(Colors.BlueGrey.Darken3);
        });
    }

    private static void ComposeExperiences(ColumnDescriptor column, IReadOnlyCollection<PdfExperienceModel> experiences)
    {
        if (experiences.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Ish tajribasi", section =>
        {
            foreach (var item in experiences)
            {
                section.Item().PaddingBottom(5).Column(entry =>
                {
                    entry.Spacing(3);
                    entry.Item().Row(row =>
                    {
                        row.RelativeItem().Text(item.Position).SemiBold().FontColor(HeadingColor);
                        row.ConstantItem(120).AlignRight().Text(FormatDateRange(item.StartDate, item.EndDate, item.IsCurrent)).FontSize(8).FontColor(MutedColor);
                    });

                    entry.Item().Text(JoinNonEmpty(" • ", item.Company, FormatExperienceType(item.ExperienceType))).FontSize(8.5f).FontColor(MutedColor);

                    if (!string.IsNullOrWhiteSpace(item.Description))
                    {
                        entry.Item().Text(item.Description).FontSize(9);
                    }
                });
            }
        });
    }

    private static void ComposeEducations(ColumnDescriptor column, IReadOnlyCollection<PdfEducationModel> educations)
    {
        if (educations.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Ta'lim", section =>
        {
            foreach (var item in educations)
            {
                section.Item().PaddingBottom(4).Row(row =>
                {
                    row.RelativeItem().Column(entry =>
                    {
                        entry.Spacing(2);
                        entry.Item().Text(item.Institution).SemiBold().FontColor(HeadingColor);
                        entry.Item().Text(JoinNonEmpty(" • ", FormatEducationType(item.EducationType), item.Degree, item.Field)).FontSize(8.5f).FontColor(MutedColor);
                    });
                    row.ConstantItem(120).AlignRight().Text(FormatDateRange(item.StartDate, item.EndDate)).FontSize(8).FontColor(MutedColor);
                });
            }
        });
    }

    private static void ComposeSkills(ColumnDescriptor column, IReadOnlyCollection<PdfSkillModel> skills)
    {
        if (skills.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Ko'nikmalar", section =>
        {
            var groups = skills
                .GroupBy(skill => string.IsNullOrWhiteSpace(skill.Category) ? "Umumiy" : skill.Category!.Trim())
                .OrderBy(group => group.Key);

            foreach (var group in groups)
            {
                section.Item().PaddingBottom(2).Text(text =>
                {
                    text.Span($"{group.Key}: ").SemiBold().FontColor(HeadingColor);
                    text.Span(string.Join(", ", group.Select(FormatSkill))).FontColor(Colors.BlueGrey.Darken3);
                });
            }
        });
    }

    private static void ComposeProjects(ColumnDescriptor column, IReadOnlyCollection<PdfProjectModel> projects)
    {
        if (projects.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Loyihalar", section =>
        {
            foreach (var item in projects)
            {
                section.Item().PaddingBottom(7).Column(entry =>
                {
                    entry.Spacing(3);
                    entry.Item().Text(item.Name).SemiBold().FontColor(HeadingColor);

                    if (!string.IsNullOrWhiteSpace(item.Description))
                    {
                        entry.Item().Text(item.Description).FontSize(9);
                    }

                    if (!string.IsNullOrWhiteSpace(item.LiveUrl))
                    {
                        AddLinkLine(entry, "Live link", item.LiveUrl, 8);
                    }

                    if (item.IsRepositoryPrivate)
                    {
                        entry.Item().Text(text =>
                        {
                            text.Span("GitHub: ").SemiBold().FontColor(MutedColor);
                            text.Span("Yopiq repository").FontColor(MutedColor);
                        });
                    }
                    else if (!string.IsNullOrWhiteSpace(item.GithubUrl))
                    {
                        AddLinkLine(entry, "GitHub", item.GithubUrl, 8);
                    }
                });
            }
        });
    }

    private static void ComposeCertificates(ColumnDescriptor column, IReadOnlyCollection<PdfCertificateModel> certificates)
    {
        if (certificates.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Sertifikatlar", section =>
        {
            foreach (var item in certificates)
            {
                section.Item().PaddingBottom(5).Column(entry =>
                {
                    entry.Spacing(2);
                    entry.Item().Text(item.Name).SemiBold().FontColor(HeadingColor);

                    var meta = JoinNonEmpty(" • ", item.Issuer, FormatDate(item.IssuedOn));
                    if (!string.IsNullOrWhiteSpace(meta))
                    {
                        entry.Item().Text(meta).FontSize(8.5f).FontColor(MutedColor);
                    }

                    if (!string.IsNullOrWhiteSpace(item.Url))
                    {
                        AddLinkLine(entry, "Sertifikat", item.Url, 8);
                    }
                });
            }
        });
    }

    private static void ComposeSection(ColumnDescriptor column, string title, Action<ColumnDescriptor> content)
    {
        column.Item().Column(section =>
        {
            section.Spacing(5);
            section.Item().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).PaddingBottom(3)
                .Text(title).FontSize(10).Bold().FontColor(HeadingColor);
            content(section);
        });
    }

    private static string FormatDateRange(DateOnly startDate, DateOnly? endDate, bool isCurrent) =>
        $"{FormatDate(startDate)} - {(isCurrent ? "Hozir" : FormatDate(endDate))}";

    private static string FormatDateRange(DateOnly? startDate, DateOnly? endDate)
    {
        var start = FormatDate(startDate);
        var end = FormatDate(endDate);

        return string.IsNullOrWhiteSpace(start) && string.IsNullOrWhiteSpace(end)
            ? string.Empty
            : $"{start} - {end}";
    }

    private static string FormatDate(DateOnly? date) => date.HasValue ? FormatDate(date.Value) : string.Empty;

    private static string FormatDate(DateOnly date) => date.ToString("yyyy-MM", System.Globalization.CultureInfo.InvariantCulture);

    private static string FormatSkill(PdfSkillModel skill) =>
        skill.Level.HasValue ? $"{skill.Name} ({skill.Level}/5)" : skill.Name;

    private static string FormatEducationType(string type) =>
        type switch
        {
            "course" => "Kurs / bootcamp",
            "self" => "Shaxsiy o'rganish",
            "mentor" => "Mentor / ustoz",
            "online" => "Onlayn kurs",
            "formal" => "Universitet / kollej",
            _ => string.Empty,
        };

    private static string FormatExperienceType(string type) =>
        type switch
        {
            "freelance" => "Freelance",
            "project" => "Shaxsiy loyiha",
            "internship" => "Amaliyot",
            "volunteer" => "Volunteer",
            "work" => "Ish joyi",
            _ => string.Empty,
        };

    private static void AddLinkLine(ColumnDescriptor column, string label, string value, float fontSize)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return;
        }

        var linkValue = NormalizeLinkValue(value);

        column.Item().Text(text =>
        {
            text.DefaultTextStyle(style => style.FontSize(fontSize));
            text.Span($"{label}: ").SemiBold().FontColor(MutedColor);

            if (IsHttpUrl(linkValue))
            {
                text.Hyperlink(linkValue, linkValue).FontColor(LinkColor).Underline();
            }
            else
            {
                text.Span(linkValue).FontColor(MutedColor);
            }
        });
    }

    private static string NormalizeLinkValue(string value)
    {
        var trimmed = value.Trim();
        if (trimmed.StartsWith("/uploads/", StringComparison.OrdinalIgnoreCase))
        {
            return $"{UploadsPublicOrigin}{trimmed}";
        }

        return trimmed;
    }

    private static bool IsHttpUrl(string? value) =>
        Uri.TryCreate(value, UriKind.Absolute, out var uri)
        && (uri.Scheme == Uri.UriSchemeHttp || uri.Scheme == Uri.UriSchemeHttps);

    private static string JoinNonEmpty(string separator, params string?[] values) =>
        string.Join(separator, values.Where(value => !string.IsNullOrWhiteSpace(value)));
}
