import { Injectable } from '@nestjs/common';
import PDFDocument = require('pdfkit');

/**
 * Port of Procraft.Infrastructure.Pdf.QuestPdfService: same A4 layout,
 * section order, Uzbek labels, date formats and link handling. QuestPDF's
 * Arial maps to the metrically-compatible Helvetica family.
 */

const UPLOADS_PUBLIC_ORIGIN = 'https://api.procraft.uz';

const HEADING_COLOR = '#263238'; // BlueGrey Darken4
const SUBTITLE_COLOR = '#455A64'; // BlueGrey Darken2
const BODY_COLOR = '#37474F'; // BlueGrey Darken3
const MUTED_COLOR = '#616161'; // Grey Darken2
const RULE_COLOR = '#E0E0E0'; // Grey Lighten2
const SECTION_RULE_COLOR = '#BDBDBD'; // Grey Lighten1
const FOOTER_COLOR = '#757575'; // Grey Darken1
const LINK_COLOR = '#1976D2'; // Blue Darken2

export interface PdfSkillModel {
  name: string;
  level: number | null;
  category: string | null;
}

export interface PdfProjectModel {
  name: string;
  description: string | null;
  githubUrl: string | null;
  isRepositoryPrivate: boolean;
  liveUrl: string | null;
}

export interface PdfExperienceModel {
  company: string;
  experienceType: string;
  position: string;
  description: string | null;
  startDate: string;
  endDate: string | null;
  isCurrent: boolean;
}

export interface PdfEducationModel {
  institution: string;
  educationType: string;
  degree: string | null;
  field: string | null;
  startDate: string | null;
  endDate: string | null;
}

export interface PdfCertificateModel {
  name: string;
  issuer: string | null;
  issuedOn: string | null;
  url: string | null;
}

export interface PdfSocialLinkModel {
  platform: string;
  url: string;
}

export interface PdfResumeModel {
  fullName: string;
  title: string | null;
  summary: string | null;
  location: string | null;
  skills: PdfSkillModel[];
  projects: PdfProjectModel[];
  experiences: PdfExperienceModel[];
  educations: PdfEducationModel[];
  certificates: PdfCertificateModel[];
  socialLinks: PdfSocialLinkModel[];
  templateSlug: string | null;
}

function formatDate(date: string | null): string {
  return date ? date.slice(0, 7) : '';
}

/** Experience overload: always "start - end|Hozir". Education overload: empty when both missing. */
function formatDateRange(startDate: string | null, endDate: string | null, isCurrent?: boolean): string {
  const start = formatDate(startDate);
  const end = isCurrent === true ? 'Hozir' : formatDate(endDate);

  if (isCurrent === undefined && start === '' && end === '') {
    return '';
  }

  return `${start} - ${end}`;
}

function formatSkill(skill: PdfSkillModel): string {
  return skill.level !== null && skill.level !== undefined ? `${skill.name} (${skill.level}/5)` : skill.name;
}

function formatEducationType(type: string): string {
  switch (type) {
    case 'course':
      return 'Kurs / bootcamp';
    case 'self':
      return "Shaxsiy o'rganish";
    case 'mentor':
      return 'Mentor / ustoz';
    case 'online':
      return 'Onlayn kurs';
    case 'formal':
      return 'Universitet / kollej';
    default:
      return '';
  }
}

function formatExperienceType(type: string): string {
  switch (type) {
    case 'freelance':
      return 'Freelance';
    case 'project':
      return 'Shaxsiy loyiha';
    case 'internship':
      return 'Amaliyot';
    case 'volunteer':
      return 'Volunteer';
    case 'work':
      return 'Ish joyi';
    default:
      return '';
  }
}

function joinNonEmpty(separator: string, ...values: Array<string | null | undefined>): string {
  return values.filter((value) => value && value.trim() !== '').join(separator);
}

function normalizeLinkValue(value: string): string {
  const trimmed = value.trim();
  if (trimmed.toLowerCase().startsWith('/uploads/')) {
    return `${UPLOADS_PUBLIC_ORIGIN}${trimmed}`;
  }
  return trimmed;
}

function isHttpUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === 'http:' || url.protocol === 'https:';
  } catch {
    return false;
  }
}

@Injectable()
export class PdfService {
  async generateResume(resume: PdfResumeModel): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 34, bufferPages: true });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      try {
        this.compose(doc, resume);

        // Footer on every page.
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i += 1) {
          doc.switchToPage(i);
          doc
            .font('Helvetica')
            .fontSize(8)
            .fillColor(FOOTER_COLOR)
            .text('Generated by Procraft', doc.page.margins.left, doc.page.height - doc.page.margins.bottom - 14, {
              width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
              align: 'center',
              lineBreak: false,
            });
        }

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  private compose(doc: PDFKit.PDFDocument, resume: PdfResumeModel): void {
    this.composeHeader(doc, resume);
    this.composeSummary(doc, resume);
    this.composeExperiences(doc, resume.experiences);
    this.composeEducations(doc, resume.educations);
    this.composeSkills(doc, resume.skills);
    this.composeProjects(doc, resume.projects);
    this.composeCertificates(doc, resume.certificates);
  }

  private contentWidth(doc: PDFKit.PDFDocument): number {
    return doc.page.width - doc.page.margins.left - doc.page.margins.right;
  }

  private composeHeader(doc: PDFKit.PDFDocument, resume: PdfResumeModel): void {
    const left = doc.page.margins.left;
    const width = this.contentWidth(doc);
    const hasLinks = resume.socialLinks.length > 0;
    const rightColumnWidth = 190;
    const leftColumnWidth = hasLinks ? width - rightColumnWidth : width;
    const top = doc.y;

    doc.font('Helvetica-Bold').fontSize(24).fillColor(HEADING_COLOR);
    doc.text(resume.fullName, left, top, { width: leftColumnWidth });

    if (resume.title && resume.title.trim() !== '') {
      doc.moveDown(0.2);
      doc.font('Helvetica-Bold').fontSize(12).fillColor(SUBTITLE_COLOR);
      doc.text(resume.title, left, doc.y, { width: leftColumnWidth });
    }

    if (resume.location && resume.location.trim() !== '') {
      doc.moveDown(0.2);
      doc.font('Helvetica-Bold').fontSize(9.5).fillColor(MUTED_COLOR);
      doc.text('Joylashuv: ', left, doc.y, { width: leftColumnWidth, continued: true });
      doc.font('Helvetica').text(resume.location);
    }

    const leftBottom = doc.y;
    let rightBottom = top;

    if (hasLinks) {
      const rightX = left + leftColumnWidth;
      doc.font('Helvetica-Bold').fontSize(8).fillColor(HEADING_COLOR);
      doc.text('Ijtimoiy havolalar', rightX, top, { width: rightColumnWidth });

      for (const link of resume.socialLinks) {
        this.addLinkLine(doc, link.platform, link.url, 8, rightX, rightColumnWidth);
      }

      rightBottom = doc.y;
    }

    const bottom = Math.max(leftBottom, rightBottom) + 4;
    doc
      .moveTo(left, bottom)
      .lineTo(left + width, bottom)
      .lineWidth(1)
      .strokeColor(RULE_COLOR)
      .stroke();

    doc.x = left;
    doc.y = bottom + 11;
  }

  private composeSection(doc: PDFKit.PDFDocument, title: string, content: () => void): void {
    const left = doc.page.margins.left;
    const width = this.contentWidth(doc);

    if (doc.y > doc.page.height - doc.page.margins.bottom - 60) {
      doc.addPage();
    }

    doc.font('Helvetica-Bold').fontSize(10).fillColor(HEADING_COLOR);
    doc.text(title, left, doc.y, { width });

    const ruleY = doc.y + 3;
    doc
      .moveTo(left, ruleY)
      .lineTo(left + width, ruleY)
      .lineWidth(1)
      .strokeColor(SECTION_RULE_COLOR)
      .stroke();

    doc.x = left;
    doc.y = ruleY + 5;

    content();

    doc.x = left;
    doc.y += 11;
  }

  private composeSummary(doc: PDFKit.PDFDocument, resume: PdfResumeModel): void {
    if (!resume.summary || resume.summary.trim() === '') {
      return;
    }

    this.composeSection(doc, "Qisqa ma'lumot", () => {
      doc.font('Helvetica').fontSize(9.5).fillColor(BODY_COLOR);
      doc.text(resume.summary!, doc.page.margins.left, doc.y, { width: this.contentWidth(doc), lineGap: 2.5 });
    });
  }

  private composeExperiences(doc: PDFKit.PDFDocument, experiences: PdfExperienceModel[]): void {
    if (experiences.length === 0) {
      return;
    }

    this.composeSection(doc, 'Ish tajribasi', () => {
      const left = doc.page.margins.left;
      const width = this.contentWidth(doc);

      for (const item of experiences) {
        const dateText = formatDateRange(item.startDate, item.endDate, item.isCurrent);

        doc.font('Helvetica-Bold').fontSize(9.5).fillColor(HEADING_COLOR);
        const rowY = doc.y;
        doc.text(item.position, left, rowY, { width: width - 120 });

        doc.font('Helvetica').fontSize(8).fillColor(MUTED_COLOR);
        doc.text(dateText, left + width - 120, rowY, { width: 120, align: 'right', lineBreak: false });

        doc.moveDown(0.2);
        doc.font('Helvetica').fontSize(8.5).fillColor(MUTED_COLOR);
        doc.text(joinNonEmpty(' • ', item.company, formatExperienceType(item.experienceType)), left, doc.y, {
          width,
        });

        if (item.description && item.description.trim() !== '') {
          doc.moveDown(0.2);
          doc.font('Helvetica').fontSize(9).fillColor('black');
          doc.text(item.description, left, doc.y, { width, lineGap: 2 });
        }

        doc.y += 5;
      }
    });
  }

  private composeEducations(doc: PDFKit.PDFDocument, educations: PdfEducationModel[]): void {
    if (educations.length === 0) {
      return;
    }

    this.composeSection(doc, "Ta'lim", () => {
      const left = doc.page.margins.left;
      const width = this.contentWidth(doc);

      for (const item of educations) {
        const rowY = doc.y;

        doc.font('Helvetica-Bold').fontSize(9.5).fillColor(HEADING_COLOR);
        doc.text(item.institution, left, rowY, { width: width - 120 });

        doc.font('Helvetica').fontSize(8).fillColor(MUTED_COLOR);
        doc.text(formatDateRange(item.startDate, item.endDate), left + width - 120, rowY, {
          width: 120,
          align: 'right',
          lineBreak: false,
        });

        doc.moveDown(0.15);
        doc.font('Helvetica').fontSize(8.5).fillColor(MUTED_COLOR);
        doc.text(
          joinNonEmpty(' • ', formatEducationType(item.educationType), item.degree, item.field),
          left,
          doc.y,
          { width },
        );

        doc.y += 4;
      }
    });
  }

  private composeSkills(doc: PDFKit.PDFDocument, skills: PdfSkillModel[]): void {
    if (skills.length === 0) {
      return;
    }

    this.composeSection(doc, "Ko'nikmalar", () => {
      const left = doc.page.margins.left;
      const width = this.contentWidth(doc);

      const groups = new Map<string, PdfSkillModel[]>();
      for (const skill of skills) {
        const key = skill.category && skill.category.trim() !== '' ? skill.category.trim() : 'Umumiy';
        (groups.get(key) ?? groups.set(key, []).get(key)!).push(skill);
      }

      const ordered = [...groups.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

      for (const [category, items] of ordered) {
        doc.font('Helvetica-Bold').fontSize(9.5).fillColor(HEADING_COLOR);
        doc.text(`${category}: `, left, doc.y, { width, continued: true });
        doc.font('Helvetica').fillColor(BODY_COLOR);
        doc.text(items.map(formatSkill).join(', '));
        doc.y += 2;
      }
    });
  }

  private composeProjects(doc: PDFKit.PDFDocument, projects: PdfProjectModel[]): void {
    if (projects.length === 0) {
      return;
    }

    this.composeSection(doc, 'Loyihalar', () => {
      const left = doc.page.margins.left;
      const width = this.contentWidth(doc);

      for (const item of projects) {
        doc.font('Helvetica-Bold').fontSize(9.5).fillColor(HEADING_COLOR);
        doc.text(item.name, left, doc.y, { width });

        if (item.description && item.description.trim() !== '') {
          doc.moveDown(0.2);
          doc.font('Helvetica').fontSize(9).fillColor('black');
          doc.text(item.description, left, doc.y, { width, lineGap: 2 });
        }

        if (item.liveUrl && item.liveUrl.trim() !== '') {
          this.addLinkLine(doc, 'Live link', item.liveUrl, 8, left, width);
        }

        if (item.isRepositoryPrivate) {
          doc.font('Helvetica-Bold').fontSize(8).fillColor(MUTED_COLOR);
          doc.text('GitHub: ', left, doc.y, { width, continued: true });
          doc.font('Helvetica').text('Yopiq repository');
        } else if (item.githubUrl && item.githubUrl.trim() !== '') {
          this.addLinkLine(doc, 'GitHub', item.githubUrl, 8, left, width);
        }

        doc.y += 7;
      }
    });
  }

  private composeCertificates(doc: PDFKit.PDFDocument, certificates: PdfCertificateModel[]): void {
    if (certificates.length === 0) {
      return;
    }

    this.composeSection(doc, 'Sertifikatlar', () => {
      const left = doc.page.margins.left;
      const width = this.contentWidth(doc);

      for (const item of certificates) {
        doc.font('Helvetica-Bold').fontSize(9.5).fillColor(HEADING_COLOR);
        doc.text(item.name, left, doc.y, { width });

        const meta = joinNonEmpty(' • ', item.issuer, formatDate(item.issuedOn));
        if (meta !== '') {
          doc.moveDown(0.15);
          doc.font('Helvetica').fontSize(8.5).fillColor(MUTED_COLOR);
          doc.text(meta, left, doc.y, { width });
        }

        if (item.url && item.url.trim() !== '') {
          this.addLinkLine(doc, 'Sertifikat', item.url, 8, left, width);
        }

        doc.y += 5;
      }
    });
  }

  private addLinkLine(
    doc: PDFKit.PDFDocument,
    label: string,
    value: string,
    fontSize: number,
    x: number,
    width: number,
  ): void {
    if (!value || value.trim() === '') {
      return;
    }

    const linkValue = normalizeLinkValue(value);

    doc.font('Helvetica-Bold').fontSize(fontSize).fillColor(MUTED_COLOR);
    doc.text(`${label}: `, x, doc.y, { width, continued: true });

    if (isHttpUrl(linkValue)) {
      doc.font('Helvetica').fillColor(LINK_COLOR).text(linkValue, { link: linkValue, underline: true });
    } else {
      doc.font('Helvetica').fillColor(MUTED_COLOR).text(linkValue);
    }
  }
}
