using Procraft.Application.Common.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Procraft.Infrastructure.Pdf;

public sealed class QuestPdfService : IPdfService
{
    public Task<byte[]> GenerateResumeAsync(PdfResumeModel resume, CancellationToken cancellationToken = default)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var bytes = Document.Create(document =>
        {
            document.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(36);
                page.DefaultTextStyle(text => text.FontFamily("Arial").FontSize(10).LineHeight(1.25f));

                page.Content().Column(column =>
                {
                    column.Spacing(12);
                    ComposeHeader(column, resume);
                    ComposeSummary(column, resume);
                    ComposeExperiences(column, resume.Experiences);
                    ComposeEducations(column, resume.Educations);
                    ComposeSkills(column, resume.Skills);
                    ComposeProjects(column, resume.Projects);
                    ComposeCertificates(column, resume.Certificates);
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Procraft").FontSize(8).FontColor(Colors.Grey.Darken1);
                });
            });
        }).GeneratePdf();

        return Task.FromResult(bytes);
    }

    private static void ComposeHeader(ColumnDescriptor column, PdfResumeModel resume)
    {
        column.Item().Text(resume.FullName).FontSize(22).Bold().FontColor(Colors.BlueGrey.Darken4);

        if (!string.IsNullOrWhiteSpace(resume.Title))
        {
            column.Item().Text(resume.Title).FontSize(12).SemiBold();
        }

        var contact = JoinNonEmpty(" | ", resume.Location, resume.Website, FormatSocialLinks(resume.SocialLinks));
        if (!string.IsNullOrWhiteSpace(contact))
        {
            column.Item().Text(contact).FontSize(9).FontColor(Colors.Grey.Darken2);
        }
    }

    private static void ComposeSummary(ColumnDescriptor column, PdfResumeModel resume)
    {
        if (string.IsNullOrWhiteSpace(resume.Summary))
        {
            return;
        }

        ComposeSection(column, "Summary", section =>
        {
            section.Item().Text(resume.Summary).FontSize(10);
        });
    }

    private static void ComposeExperiences(ColumnDescriptor column, IReadOnlyCollection<PdfExperienceModel> experiences)
    {
        if (experiences.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Experience", section =>
        {
            foreach (var item in experiences)
            {
                section.Item().Column(entry =>
                {
                    entry.Spacing(2);
                    entry.Item().Row(row =>
                    {
                        row.RelativeItem().Text($"{item.Position} - {item.Company}").SemiBold();
                        row.ConstantItem(130).AlignRight().Text(FormatDateRange(item.StartDate, item.EndDate, item.IsCurrent)).FontSize(9);
                    });

                    if (!string.IsNullOrWhiteSpace(item.Description))
                    {
                        entry.Item().Text(item.Description).FontSize(9);
                    }
                });
            }
        });
    }

    private static void ComposeEducations(ColumnDescriptor column, IReadOnlyCollection<PdfEducationModel> educations)
    {
        if (educations.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Education", section =>
        {
            foreach (var item in educations)
            {
                section.Item().Row(row =>
                {
                    row.RelativeItem().Text(JoinNonEmpty(", ", item.Institution, JoinNonEmpty(" - ", item.Degree, item.Field))).SemiBold();
                    row.ConstantItem(130).AlignRight().Text(FormatDateRange(item.StartDate, item.EndDate)).FontSize(9);
                });
            }
        });
    }

    private static void ComposeSkills(ColumnDescriptor column, IReadOnlyCollection<PdfSkillModel> skills)
    {
        if (skills.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Skills", section =>
        {
            var skillText = string.Join(", ", skills.Select(skill =>
                skill.Level.HasValue
                    ? $"{skill.Name} ({skill.Level}/5)"
                    : skill.Name));

            section.Item().Text(skillText).FontSize(10);
        });
    }

    private static void ComposeProjects(ColumnDescriptor column, IReadOnlyCollection<PdfProjectModel> projects)
    {
        if (projects.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Projects", section =>
        {
            foreach (var item in projects)
            {
                section.Item().Column(entry =>
                {
                    entry.Spacing(2);
                    entry.Item().Text(item.Name).SemiBold();

                    if (!string.IsNullOrWhiteSpace(item.Description))
                    {
                        entry.Item().Text(item.Description).FontSize(9);
                    }

                    var links = JoinNonEmpty(" | ", item.GithubUrl, item.LiveUrl);
                    if (!string.IsNullOrWhiteSpace(links))
                    {
                        entry.Item().Text(links).FontSize(8).FontColor(Colors.Grey.Darken2);
                    }
                });
            }
        });
    }

    private static void ComposeCertificates(ColumnDescriptor column, IReadOnlyCollection<PdfCertificateModel> certificates)
    {
        if (certificates.Count == 0)
        {
            return;
        }

        ComposeSection(column, "Certificates", section =>
        {
            foreach (var item in certificates)
            {
                section.Item().Text(JoinNonEmpty(" | ", item.Name, item.Issuer, FormatDate(item.IssuedOn), item.Url));
            }
        });
    }

    private static void ComposeSection(ColumnDescriptor column, string title, Action<ColumnDescriptor> content)
    {
        column.Item().Column(section =>
        {
            section.Spacing(5);
            section.Item().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).PaddingBottom(3)
                .Text(title.ToUpperInvariant()).FontSize(10).Bold().FontColor(Colors.BlueGrey.Darken4);
            content(section);
        });
    }

    private static string FormatDateRange(DateOnly startDate, DateOnly? endDate, bool isCurrent) =>
        $"{FormatDate(startDate)} - {(isCurrent ? "Present" : FormatDate(endDate))}";

    private static string FormatDateRange(DateOnly? startDate, DateOnly? endDate)
    {
        var start = FormatDate(startDate);
        var end = FormatDate(endDate);

        return string.IsNullOrWhiteSpace(start) && string.IsNullOrWhiteSpace(end)
            ? string.Empty
            : $"{start} - {end}";
    }

    private static string FormatDate(DateOnly? date) => date.HasValue ? FormatDate(date.Value) : string.Empty;

    private static string FormatDate(DateOnly date) => date.ToString("MMM yyyy", System.Globalization.CultureInfo.InvariantCulture);

    private static string FormatSocialLinks(IReadOnlyCollection<PdfSocialLinkModel> links) =>
        string.Join(" | ", links.Select(link => $"{link.Platform}: {link.Url}"));

    private static string JoinNonEmpty(string separator, params string?[] values) =>
        string.Join(separator, values.Where(value => !string.IsNullOrWhiteSpace(value)));
}
